// Phase 4 explicit 200-lesson curriculum for Level 3A.
export const curriculum3A = {
  "id": "3A",
  "title": "Adding 1, 2, and 3",
  "lessonCount": 200,
  "lessons": [
    {
      "id": "3A001",
      "displayId": "3A-1",
      "level": "3A",
      "lessonNumber": 1,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A002",
      "displayId": "3A-2",
      "level": "3A",
      "lessonNumber": 2,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A003",
      "displayId": "3A-3",
      "level": "3A",
      "lessonNumber": 3,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A004",
      "displayId": "3A-4",
      "level": "3A",
      "lessonNumber": 4,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A005",
      "displayId": "3A-5",
      "level": "3A",
      "lessonNumber": 5,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A006",
      "displayId": "3A-6",
      "level": "3A",
      "lessonNumber": 6,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A007",
      "displayId": "3A-7",
      "level": "3A",
      "lessonNumber": 7,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A008",
      "displayId": "3A-8",
      "level": "3A",
      "lessonNumber": 8,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A009",
      "displayId": "3A-9",
      "level": "3A",
      "lessonNumber": 9,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A010",
      "displayId": "3A-10",
      "level": "3A",
      "lessonNumber": 10,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A011",
      "displayId": "3A-11",
      "level": "3A",
      "lessonNumber": 11,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A012",
      "displayId": "3A-12",
      "level": "3A",
      "lessonNumber": 12,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A013",
      "displayId": "3A-13",
      "level": "3A",
      "lessonNumber": 13,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A014",
      "displayId": "3A-14",
      "level": "3A",
      "lessonNumber": 14,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A015",
      "displayId": "3A-15",
      "level": "3A",
      "lessonNumber": 15,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A016",
      "displayId": "3A-16",
      "level": "3A",
      "lessonNumber": 16,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A017",
      "displayId": "3A-17",
      "level": "3A",
      "lessonNumber": 17,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A018",
      "displayId": "3A-18",
      "level": "3A",
      "lessonNumber": 18,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A019",
      "displayId": "3A-19",
      "level": "3A",
      "lessonNumber": 19,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A020",
      "displayId": "3A-20",
      "level": "3A",
      "lessonNumber": 20,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A021",
      "displayId": "3A-21",
      "level": "3A",
      "lessonNumber": 21,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A022",
      "displayId": "3A-22",
      "level": "3A",
      "lessonNumber": 22,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A023",
      "displayId": "3A-23",
      "level": "3A",
      "lessonNumber": 23,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A024",
      "displayId": "3A-24",
      "level": "3A",
      "lessonNumber": 24,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A025",
      "displayId": "3A-25",
      "level": "3A",
      "lessonNumber": 25,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A026",
      "displayId": "3A-26",
      "level": "3A",
      "lessonNumber": 26,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A027",
      "displayId": "3A-27",
      "level": "3A",
      "lessonNumber": 27,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A028",
      "displayId": "3A-28",
      "level": "3A",
      "lessonNumber": 28,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A029",
      "displayId": "3A-29",
      "level": "3A",
      "lessonNumber": 29,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A030",
      "displayId": "3A-30",
      "level": "3A",
      "lessonNumber": 30,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A031",
      "displayId": "3A-31",
      "level": "3A",
      "lessonNumber": 31,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A032",
      "displayId": "3A-32",
      "level": "3A",
      "lessonNumber": 32,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A033",
      "displayId": "3A-33",
      "level": "3A",
      "lessonNumber": 33,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A034",
      "displayId": "3A-34",
      "level": "3A",
      "lessonNumber": 34,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A035",
      "displayId": "3A-35",
      "level": "3A",
      "lessonNumber": 35,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A036",
      "displayId": "3A-36",
      "level": "3A",
      "lessonNumber": 36,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A037",
      "displayId": "3A-37",
      "level": "3A",
      "lessonNumber": 37,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A038",
      "displayId": "3A-38",
      "level": "3A",
      "lessonNumber": 38,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A039",
      "displayId": "3A-39",
      "level": "3A",
      "lessonNumber": 39,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A040",
      "displayId": "3A-40",
      "level": "3A",
      "lessonNumber": 40,
      "unit": "Numbers up to 100",
      "skill": "number_reading_1_100",
      "mode": "number_reading",
      "maxValue": 100,
      "questionCount": 10
    },
    {
      "id": "3A041",
      "displayId": "3A-41",
      "level": "3A",
      "lessonNumber": 41,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A042",
      "displayId": "3A-42",
      "level": "3A",
      "lessonNumber": 42,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A043",
      "displayId": "3A-43",
      "level": "3A",
      "lessonNumber": 43,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A044",
      "displayId": "3A-44",
      "level": "3A",
      "lessonNumber": 44,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A045",
      "displayId": "3A-45",
      "level": "3A",
      "lessonNumber": 45,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A046",
      "displayId": "3A-46",
      "level": "3A",
      "lessonNumber": 46,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A047",
      "displayId": "3A-47",
      "level": "3A",
      "lessonNumber": 47,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A048",
      "displayId": "3A-48",
      "level": "3A",
      "lessonNumber": 48,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A049",
      "displayId": "3A-49",
      "level": "3A",
      "lessonNumber": 49,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A050",
      "displayId": "3A-50",
      "level": "3A",
      "lessonNumber": 50,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A051",
      "displayId": "3A-51",
      "level": "3A",
      "lessonNumber": 51,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A052",
      "displayId": "3A-52",
      "level": "3A",
      "lessonNumber": 52,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A053",
      "displayId": "3A-53",
      "level": "3A",
      "lessonNumber": 53,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A054",
      "displayId": "3A-54",
      "level": "3A",
      "lessonNumber": 54,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A055",
      "displayId": "3A-55",
      "level": "3A",
      "lessonNumber": 55,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A056",
      "displayId": "3A-56",
      "level": "3A",
      "lessonNumber": 56,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A057",
      "displayId": "3A-57",
      "level": "3A",
      "lessonNumber": 57,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A058",
      "displayId": "3A-58",
      "level": "3A",
      "lessonNumber": 58,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A059",
      "displayId": "3A-59",
      "level": "3A",
      "lessonNumber": 59,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A060",
      "displayId": "3A-60",
      "level": "3A",
      "lessonNumber": 60,
      "unit": "Numbers up to 120",
      "skill": "number_reading_1_120",
      "mode": "number_reading",
      "maxValue": 120,
      "questionCount": 10
    },
    {
      "id": "3A061",
      "displayId": "3A-61",
      "level": "3A",
      "lessonNumber": 61,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A062",
      "displayId": "3A-62",
      "level": "3A",
      "lessonNumber": 62,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A063",
      "displayId": "3A-63",
      "level": "3A",
      "lessonNumber": 63,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A064",
      "displayId": "3A-64",
      "level": "3A",
      "lessonNumber": 64,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A065",
      "displayId": "3A-65",
      "level": "3A",
      "lessonNumber": 65,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A066",
      "displayId": "3A-66",
      "level": "3A",
      "lessonNumber": 66,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A067",
      "displayId": "3A-67",
      "level": "3A",
      "lessonNumber": 67,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A068",
      "displayId": "3A-68",
      "level": "3A",
      "lessonNumber": 68,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A069",
      "displayId": "3A-69",
      "level": "3A",
      "lessonNumber": 69,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A070",
      "displayId": "3A-70",
      "level": "3A",
      "lessonNumber": 70,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A071",
      "displayId": "3A-71",
      "level": "3A",
      "lessonNumber": 71,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A072",
      "displayId": "3A-72",
      "level": "3A",
      "lessonNumber": 72,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A073",
      "displayId": "3A-73",
      "level": "3A",
      "lessonNumber": 73,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A074",
      "displayId": "3A-74",
      "level": "3A",
      "lessonNumber": 74,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A075",
      "displayId": "3A-75",
      "level": "3A",
      "lessonNumber": 75,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A076",
      "displayId": "3A-76",
      "level": "3A",
      "lessonNumber": 76,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A077",
      "displayId": "3A-77",
      "level": "3A",
      "lessonNumber": 77,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A078",
      "displayId": "3A-78",
      "level": "3A",
      "lessonNumber": 78,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A079",
      "displayId": "3A-79",
      "level": "3A",
      "lessonNumber": 79,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A080",
      "displayId": "3A-80",
      "level": "3A",
      "lessonNumber": 80,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A081",
      "displayId": "3A-81",
      "level": "3A",
      "lessonNumber": 81,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A082",
      "displayId": "3A-82",
      "level": "3A",
      "lessonNumber": 82,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A083",
      "displayId": "3A-83",
      "level": "3A",
      "lessonNumber": 83,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A084",
      "displayId": "3A-84",
      "level": "3A",
      "lessonNumber": 84,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A085",
      "displayId": "3A-85",
      "level": "3A",
      "lessonNumber": 85,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A086",
      "displayId": "3A-86",
      "level": "3A",
      "lessonNumber": 86,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A087",
      "displayId": "3A-87",
      "level": "3A",
      "lessonNumber": 87,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A088",
      "displayId": "3A-88",
      "level": "3A",
      "lessonNumber": 88,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A089",
      "displayId": "3A-89",
      "level": "3A",
      "lessonNumber": 89,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A090",
      "displayId": "3A-90",
      "level": "3A",
      "lessonNumber": 90,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A091",
      "displayId": "3A-91",
      "level": "3A",
      "lessonNumber": 91,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A092",
      "displayId": "3A-92",
      "level": "3A",
      "lessonNumber": 92,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A093",
      "displayId": "3A-93",
      "level": "3A",
      "lessonNumber": 93,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A094",
      "displayId": "3A-94",
      "level": "3A",
      "lessonNumber": 94,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A095",
      "displayId": "3A-95",
      "level": "3A",
      "lessonNumber": 95,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A096",
      "displayId": "3A-96",
      "level": "3A",
      "lessonNumber": 96,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A097",
      "displayId": "3A-97",
      "level": "3A",
      "lessonNumber": 97,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A098",
      "displayId": "3A-98",
      "level": "3A",
      "lessonNumber": 98,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A099",
      "displayId": "3A-99",
      "level": "3A",
      "lessonNumber": 99,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A100",
      "displayId": "3A-100",
      "level": "3A",
      "lessonNumber": 100,
      "unit": "Adding 1",
      "skill": "adding_1",
      "mode": "addition",
      "maxValue": 1,
      "questionCount": 10
    },
    {
      "id": "3A101",
      "displayId": "3A-101",
      "level": "3A",
      "lessonNumber": 101,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A102",
      "displayId": "3A-102",
      "level": "3A",
      "lessonNumber": 102,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A103",
      "displayId": "3A-103",
      "level": "3A",
      "lessonNumber": 103,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A104",
      "displayId": "3A-104",
      "level": "3A",
      "lessonNumber": 104,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A105",
      "displayId": "3A-105",
      "level": "3A",
      "lessonNumber": 105,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A106",
      "displayId": "3A-106",
      "level": "3A",
      "lessonNumber": 106,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A107",
      "displayId": "3A-107",
      "level": "3A",
      "lessonNumber": 107,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A108",
      "displayId": "3A-108",
      "level": "3A",
      "lessonNumber": 108,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A109",
      "displayId": "3A-109",
      "level": "3A",
      "lessonNumber": 109,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A110",
      "displayId": "3A-110",
      "level": "3A",
      "lessonNumber": 110,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A111",
      "displayId": "3A-111",
      "level": "3A",
      "lessonNumber": 111,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A112",
      "displayId": "3A-112",
      "level": "3A",
      "lessonNumber": 112,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A113",
      "displayId": "3A-113",
      "level": "3A",
      "lessonNumber": 113,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A114",
      "displayId": "3A-114",
      "level": "3A",
      "lessonNumber": 114,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A115",
      "displayId": "3A-115",
      "level": "3A",
      "lessonNumber": 115,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A116",
      "displayId": "3A-116",
      "level": "3A",
      "lessonNumber": 116,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A117",
      "displayId": "3A-117",
      "level": "3A",
      "lessonNumber": 117,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A118",
      "displayId": "3A-118",
      "level": "3A",
      "lessonNumber": 118,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A119",
      "displayId": "3A-119",
      "level": "3A",
      "lessonNumber": 119,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A120",
      "displayId": "3A-120",
      "level": "3A",
      "lessonNumber": 120,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A121",
      "displayId": "3A-121",
      "level": "3A",
      "lessonNumber": 121,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A122",
      "displayId": "3A-122",
      "level": "3A",
      "lessonNumber": 122,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A123",
      "displayId": "3A-123",
      "level": "3A",
      "lessonNumber": 123,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A124",
      "displayId": "3A-124",
      "level": "3A",
      "lessonNumber": 124,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A125",
      "displayId": "3A-125",
      "level": "3A",
      "lessonNumber": 125,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A126",
      "displayId": "3A-126",
      "level": "3A",
      "lessonNumber": 126,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A127",
      "displayId": "3A-127",
      "level": "3A",
      "lessonNumber": 127,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A128",
      "displayId": "3A-128",
      "level": "3A",
      "lessonNumber": 128,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A129",
      "displayId": "3A-129",
      "level": "3A",
      "lessonNumber": 129,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A130",
      "displayId": "3A-130",
      "level": "3A",
      "lessonNumber": 130,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A131",
      "displayId": "3A-131",
      "level": "3A",
      "lessonNumber": 131,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A132",
      "displayId": "3A-132",
      "level": "3A",
      "lessonNumber": 132,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A133",
      "displayId": "3A-133",
      "level": "3A",
      "lessonNumber": 133,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A134",
      "displayId": "3A-134",
      "level": "3A",
      "lessonNumber": 134,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A135",
      "displayId": "3A-135",
      "level": "3A",
      "lessonNumber": 135,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A136",
      "displayId": "3A-136",
      "level": "3A",
      "lessonNumber": 136,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A137",
      "displayId": "3A-137",
      "level": "3A",
      "lessonNumber": 137,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A138",
      "displayId": "3A-138",
      "level": "3A",
      "lessonNumber": 138,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A139",
      "displayId": "3A-139",
      "level": "3A",
      "lessonNumber": 139,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A140",
      "displayId": "3A-140",
      "level": "3A",
      "lessonNumber": 140,
      "unit": "Adding 2",
      "skill": "adding_2",
      "mode": "addition",
      "maxValue": 2,
      "questionCount": 10
    },
    {
      "id": "3A141",
      "displayId": "3A-141",
      "level": "3A",
      "lessonNumber": 141,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A142",
      "displayId": "3A-142",
      "level": "3A",
      "lessonNumber": 142,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A143",
      "displayId": "3A-143",
      "level": "3A",
      "lessonNumber": 143,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A144",
      "displayId": "3A-144",
      "level": "3A",
      "lessonNumber": 144,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A145",
      "displayId": "3A-145",
      "level": "3A",
      "lessonNumber": 145,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A146",
      "displayId": "3A-146",
      "level": "3A",
      "lessonNumber": 146,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A147",
      "displayId": "3A-147",
      "level": "3A",
      "lessonNumber": 147,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A148",
      "displayId": "3A-148",
      "level": "3A",
      "lessonNumber": 148,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A149",
      "displayId": "3A-149",
      "level": "3A",
      "lessonNumber": 149,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A150",
      "displayId": "3A-150",
      "level": "3A",
      "lessonNumber": 150,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A151",
      "displayId": "3A-151",
      "level": "3A",
      "lessonNumber": 151,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A152",
      "displayId": "3A-152",
      "level": "3A",
      "lessonNumber": 152,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A153",
      "displayId": "3A-153",
      "level": "3A",
      "lessonNumber": 153,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A154",
      "displayId": "3A-154",
      "level": "3A",
      "lessonNumber": 154,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A155",
      "displayId": "3A-155",
      "level": "3A",
      "lessonNumber": 155,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A156",
      "displayId": "3A-156",
      "level": "3A",
      "lessonNumber": 156,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A157",
      "displayId": "3A-157",
      "level": "3A",
      "lessonNumber": 157,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A158",
      "displayId": "3A-158",
      "level": "3A",
      "lessonNumber": 158,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A159",
      "displayId": "3A-159",
      "level": "3A",
      "lessonNumber": 159,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A160",
      "displayId": "3A-160",
      "level": "3A",
      "lessonNumber": 160,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A161",
      "displayId": "3A-161",
      "level": "3A",
      "lessonNumber": 161,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A162",
      "displayId": "3A-162",
      "level": "3A",
      "lessonNumber": 162,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A163",
      "displayId": "3A-163",
      "level": "3A",
      "lessonNumber": 163,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A164",
      "displayId": "3A-164",
      "level": "3A",
      "lessonNumber": 164,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A165",
      "displayId": "3A-165",
      "level": "3A",
      "lessonNumber": 165,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A166",
      "displayId": "3A-166",
      "level": "3A",
      "lessonNumber": 166,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A167",
      "displayId": "3A-167",
      "level": "3A",
      "lessonNumber": 167,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A168",
      "displayId": "3A-168",
      "level": "3A",
      "lessonNumber": 168,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A169",
      "displayId": "3A-169",
      "level": "3A",
      "lessonNumber": 169,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A170",
      "displayId": "3A-170",
      "level": "3A",
      "lessonNumber": 170,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A171",
      "displayId": "3A-171",
      "level": "3A",
      "lessonNumber": 171,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A172",
      "displayId": "3A-172",
      "level": "3A",
      "lessonNumber": 172,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A173",
      "displayId": "3A-173",
      "level": "3A",
      "lessonNumber": 173,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A174",
      "displayId": "3A-174",
      "level": "3A",
      "lessonNumber": 174,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A175",
      "displayId": "3A-175",
      "level": "3A",
      "lessonNumber": 175,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A176",
      "displayId": "3A-176",
      "level": "3A",
      "lessonNumber": 176,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A177",
      "displayId": "3A-177",
      "level": "3A",
      "lessonNumber": 177,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A178",
      "displayId": "3A-178",
      "level": "3A",
      "lessonNumber": 178,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A179",
      "displayId": "3A-179",
      "level": "3A",
      "lessonNumber": 179,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A180",
      "displayId": "3A-180",
      "level": "3A",
      "lessonNumber": 180,
      "unit": "Adding 3",
      "skill": "adding_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A181",
      "displayId": "3A-181",
      "level": "3A",
      "lessonNumber": 181,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A182",
      "displayId": "3A-182",
      "level": "3A",
      "lessonNumber": 182,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A183",
      "displayId": "3A-183",
      "level": "3A",
      "lessonNumber": 183,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A184",
      "displayId": "3A-184",
      "level": "3A",
      "lessonNumber": 184,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A185",
      "displayId": "3A-185",
      "level": "3A",
      "lessonNumber": 185,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A186",
      "displayId": "3A-186",
      "level": "3A",
      "lessonNumber": 186,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A187",
      "displayId": "3A-187",
      "level": "3A",
      "lessonNumber": 187,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A188",
      "displayId": "3A-188",
      "level": "3A",
      "lessonNumber": 188,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A189",
      "displayId": "3A-189",
      "level": "3A",
      "lessonNumber": 189,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A190",
      "displayId": "3A-190",
      "level": "3A",
      "lessonNumber": 190,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A191",
      "displayId": "3A-191",
      "level": "3A",
      "lessonNumber": 191,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A192",
      "displayId": "3A-192",
      "level": "3A",
      "lessonNumber": 192,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A193",
      "displayId": "3A-193",
      "level": "3A",
      "lessonNumber": 193,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A194",
      "displayId": "3A-194",
      "level": "3A",
      "lessonNumber": 194,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A195",
      "displayId": "3A-195",
      "level": "3A",
      "lessonNumber": 195,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A196",
      "displayId": "3A-196",
      "level": "3A",
      "lessonNumber": 196,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A197",
      "displayId": "3A-197",
      "level": "3A",
      "lessonNumber": 197,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A198",
      "displayId": "3A-198",
      "level": "3A",
      "lessonNumber": 198,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A199",
      "displayId": "3A-199",
      "level": "3A",
      "lessonNumber": 199,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    },
    {
      "id": "3A200",
      "displayId": "3A-200",
      "level": "3A",
      "lessonNumber": 200,
      "unit": "Adding up to 3",
      "skill": "adding_up_to_3",
      "mode": "addition",
      "maxValue": 3,
      "questionCount": 10
    }
  ]
};
