// Auto-generated curriculum metadata. 200 entries are worksheet-equivalent pages; question counts vary by topic phase.
export const curriculum5A = {
  "id": "5A",
  "title": "Number Reading & Sequences",
  "lessonCount": 200,
  "lessons": [
    {
      "id": "5A001",
      "displayId": "5A-1",
      "level": "5A",
      "lessonNumber": 1,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A002",
      "displayId": "5A-2",
      "level": "5A",
      "lessonNumber": 2,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A003",
      "displayId": "5A-3",
      "level": "5A",
      "lessonNumber": 3,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A004",
      "displayId": "5A-4",
      "level": "5A",
      "lessonNumber": 4,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A005",
      "displayId": "5A-5",
      "level": "5A",
      "lessonNumber": 5,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A006",
      "displayId": "5A-6",
      "level": "5A",
      "lessonNumber": 6,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A007",
      "displayId": "5A-7",
      "level": "5A",
      "lessonNumber": 7,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A008",
      "displayId": "5A-8",
      "level": "5A",
      "lessonNumber": 8,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A009",
      "displayId": "5A-9",
      "level": "5A",
      "lessonNumber": 9,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A010",
      "displayId": "5A-10",
      "level": "5A",
      "lessonNumber": 10,
      "unit": "Number Reading up to 30 \u2014 Part 1",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A011",
      "displayId": "5A-11",
      "level": "5A",
      "lessonNumber": 11,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A012",
      "displayId": "5A-12",
      "level": "5A",
      "lessonNumber": 12,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A013",
      "displayId": "5A-13",
      "level": "5A",
      "lessonNumber": 13,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A014",
      "displayId": "5A-14",
      "level": "5A",
      "lessonNumber": 14,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A015",
      "displayId": "5A-15",
      "level": "5A",
      "lessonNumber": 15,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A016",
      "displayId": "5A-16",
      "level": "5A",
      "lessonNumber": 16,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A017",
      "displayId": "5A-17",
      "level": "5A",
      "lessonNumber": 17,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A018",
      "displayId": "5A-18",
      "level": "5A",
      "lessonNumber": 18,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A019",
      "displayId": "5A-19",
      "level": "5A",
      "lessonNumber": 19,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A020",
      "displayId": "5A-20",
      "level": "5A",
      "lessonNumber": 20,
      "unit": "Number Reading up to 30 \u2014 Part 2",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A021",
      "displayId": "5A-21",
      "level": "5A",
      "lessonNumber": 21,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A022",
      "displayId": "5A-22",
      "level": "5A",
      "lessonNumber": 22,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A023",
      "displayId": "5A-23",
      "level": "5A",
      "lessonNumber": 23,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A024",
      "displayId": "5A-24",
      "level": "5A",
      "lessonNumber": 24,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A025",
      "displayId": "5A-25",
      "level": "5A",
      "lessonNumber": 25,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A026",
      "displayId": "5A-26",
      "level": "5A",
      "lessonNumber": 26,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A027",
      "displayId": "5A-27",
      "level": "5A",
      "lessonNumber": 27,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A028",
      "displayId": "5A-28",
      "level": "5A",
      "lessonNumber": 28,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A029",
      "displayId": "5A-29",
      "level": "5A",
      "lessonNumber": 29,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A030",
      "displayId": "5A-30",
      "level": "5A",
      "lessonNumber": 30,
      "unit": "Number Reading up to 30 \u2014 Part 3",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A031",
      "displayId": "5A-31",
      "level": "5A",
      "lessonNumber": 31,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A032",
      "displayId": "5A-32",
      "level": "5A",
      "lessonNumber": 32,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A033",
      "displayId": "5A-33",
      "level": "5A",
      "lessonNumber": 33,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A034",
      "displayId": "5A-34",
      "level": "5A",
      "lessonNumber": 34,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A035",
      "displayId": "5A-35",
      "level": "5A",
      "lessonNumber": 35,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A036",
      "displayId": "5A-36",
      "level": "5A",
      "lessonNumber": 36,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A037",
      "displayId": "5A-37",
      "level": "5A",
      "lessonNumber": 37,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A038",
      "displayId": "5A-38",
      "level": "5A",
      "lessonNumber": 38,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A039",
      "displayId": "5A-39",
      "level": "5A",
      "lessonNumber": 39,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A040",
      "displayId": "5A-40",
      "level": "5A",
      "lessonNumber": 40,
      "unit": "Number Reading up to 30 \u2014 Part 4",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A041",
      "displayId": "5A-41",
      "level": "5A",
      "lessonNumber": 41,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A042",
      "displayId": "5A-42",
      "level": "5A",
      "lessonNumber": 42,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A043",
      "displayId": "5A-43",
      "level": "5A",
      "lessonNumber": 43,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A044",
      "displayId": "5A-44",
      "level": "5A",
      "lessonNumber": 44,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A045",
      "displayId": "5A-45",
      "level": "5A",
      "lessonNumber": 45,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A046",
      "displayId": "5A-46",
      "level": "5A",
      "lessonNumber": 46,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A047",
      "displayId": "5A-47",
      "level": "5A",
      "lessonNumber": 47,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A048",
      "displayId": "5A-48",
      "level": "5A",
      "lessonNumber": 48,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A049",
      "displayId": "5A-49",
      "level": "5A",
      "lessonNumber": 49,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A050",
      "displayId": "5A-50",
      "level": "5A",
      "lessonNumber": 50,
      "unit": "Number Reading up to 30 \u2014 Part 5",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A051",
      "displayId": "5A-51",
      "level": "5A",
      "lessonNumber": 51,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A052",
      "displayId": "5A-52",
      "level": "5A",
      "lessonNumber": 52,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A053",
      "displayId": "5A-53",
      "level": "5A",
      "lessonNumber": 53,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A054",
      "displayId": "5A-54",
      "level": "5A",
      "lessonNumber": 54,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A055",
      "displayId": "5A-55",
      "level": "5A",
      "lessonNumber": 55,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A056",
      "displayId": "5A-56",
      "level": "5A",
      "lessonNumber": 56,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A057",
      "displayId": "5A-57",
      "level": "5A",
      "lessonNumber": 57,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A058",
      "displayId": "5A-58",
      "level": "5A",
      "lessonNumber": 58,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A059",
      "displayId": "5A-59",
      "level": "5A",
      "lessonNumber": 59,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A060",
      "displayId": "5A-60",
      "level": "5A",
      "lessonNumber": 60,
      "unit": "Number Reading up to 30 \u2014 Part 6",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A061",
      "displayId": "5A-61",
      "level": "5A",
      "lessonNumber": 61,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A062",
      "displayId": "5A-62",
      "level": "5A",
      "lessonNumber": 62,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A063",
      "displayId": "5A-63",
      "level": "5A",
      "lessonNumber": 63,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A064",
      "displayId": "5A-64",
      "level": "5A",
      "lessonNumber": 64,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A065",
      "displayId": "5A-65",
      "level": "5A",
      "lessonNumber": 65,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A066",
      "displayId": "5A-66",
      "level": "5A",
      "lessonNumber": 66,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A067",
      "displayId": "5A-67",
      "level": "5A",
      "lessonNumber": 67,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A068",
      "displayId": "5A-68",
      "level": "5A",
      "lessonNumber": 68,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A069",
      "displayId": "5A-69",
      "level": "5A",
      "lessonNumber": 69,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A070",
      "displayId": "5A-70",
      "level": "5A",
      "lessonNumber": 70,
      "unit": "Number Reading up to 30 \u2014 Part 7",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A071",
      "displayId": "5A-71",
      "level": "5A",
      "lessonNumber": 71,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A072",
      "displayId": "5A-72",
      "level": "5A",
      "lessonNumber": 72,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A073",
      "displayId": "5A-73",
      "level": "5A",
      "lessonNumber": 73,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A074",
      "displayId": "5A-74",
      "level": "5A",
      "lessonNumber": 74,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A075",
      "displayId": "5A-75",
      "level": "5A",
      "lessonNumber": 75,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A076",
      "displayId": "5A-76",
      "level": "5A",
      "lessonNumber": 76,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A077",
      "displayId": "5A-77",
      "level": "5A",
      "lessonNumber": 77,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A078",
      "displayId": "5A-78",
      "level": "5A",
      "lessonNumber": 78,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A079",
      "displayId": "5A-79",
      "level": "5A",
      "lessonNumber": 79,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A080",
      "displayId": "5A-80",
      "level": "5A",
      "lessonNumber": 80,
      "unit": "Number Reading up to 30 \u2014 Part 8",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A081",
      "displayId": "5A-81",
      "level": "5A",
      "lessonNumber": 81,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A082",
      "displayId": "5A-82",
      "level": "5A",
      "lessonNumber": 82,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A083",
      "displayId": "5A-83",
      "level": "5A",
      "lessonNumber": 83,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A084",
      "displayId": "5A-84",
      "level": "5A",
      "lessonNumber": 84,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A085",
      "displayId": "5A-85",
      "level": "5A",
      "lessonNumber": 85,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A086",
      "displayId": "5A-86",
      "level": "5A",
      "lessonNumber": 86,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A087",
      "displayId": "5A-87",
      "level": "5A",
      "lessonNumber": 87,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A088",
      "displayId": "5A-88",
      "level": "5A",
      "lessonNumber": 88,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A089",
      "displayId": "5A-89",
      "level": "5A",
      "lessonNumber": 89,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A090",
      "displayId": "5A-90",
      "level": "5A",
      "lessonNumber": 90,
      "unit": "Number Reading up to 30 \u2014 Part 9",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A091",
      "displayId": "5A-91",
      "level": "5A",
      "lessonNumber": 91,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A092",
      "displayId": "5A-92",
      "level": "5A",
      "lessonNumber": 92,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A093",
      "displayId": "5A-93",
      "level": "5A",
      "lessonNumber": 93,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A094",
      "displayId": "5A-94",
      "level": "5A",
      "lessonNumber": 94,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A095",
      "displayId": "5A-95",
      "level": "5A",
      "lessonNumber": 95,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A096",
      "displayId": "5A-96",
      "level": "5A",
      "lessonNumber": 96,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A097",
      "displayId": "5A-97",
      "level": "5A",
      "lessonNumber": 97,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A098",
      "displayId": "5A-98",
      "level": "5A",
      "lessonNumber": 98,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A099",
      "displayId": "5A-99",
      "level": "5A",
      "lessonNumber": 99,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A100",
      "displayId": "5A-100",
      "level": "5A",
      "lessonNumber": 100,
      "unit": "Number Reading up to 30 \u2014 Part 10",
      "title": "Number Reading up to 30",
      "skill": "number_reading_1_30",
      "mode": "number_reading",
      "maxValue": 30,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A101",
      "displayId": "5A-101",
      "level": "5A",
      "lessonNumber": 101,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A102",
      "displayId": "5A-102",
      "level": "5A",
      "lessonNumber": 102,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A103",
      "displayId": "5A-103",
      "level": "5A",
      "lessonNumber": 103,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A104",
      "displayId": "5A-104",
      "level": "5A",
      "lessonNumber": 104,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A105",
      "displayId": "5A-105",
      "level": "5A",
      "lessonNumber": 105,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A106",
      "displayId": "5A-106",
      "level": "5A",
      "lessonNumber": 106,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A107",
      "displayId": "5A-107",
      "level": "5A",
      "lessonNumber": 107,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A108",
      "displayId": "5A-108",
      "level": "5A",
      "lessonNumber": 108,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A109",
      "displayId": "5A-109",
      "level": "5A",
      "lessonNumber": 109,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A110",
      "displayId": "5A-110",
      "level": "5A",
      "lessonNumber": 110,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 1",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A111",
      "displayId": "5A-111",
      "level": "5A",
      "lessonNumber": 111,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A112",
      "displayId": "5A-112",
      "level": "5A",
      "lessonNumber": 112,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A113",
      "displayId": "5A-113",
      "level": "5A",
      "lessonNumber": 113,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A114",
      "displayId": "5A-114",
      "level": "5A",
      "lessonNumber": 114,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A115",
      "displayId": "5A-115",
      "level": "5A",
      "lessonNumber": 115,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A116",
      "displayId": "5A-116",
      "level": "5A",
      "lessonNumber": 116,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A117",
      "displayId": "5A-117",
      "level": "5A",
      "lessonNumber": 117,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A118",
      "displayId": "5A-118",
      "level": "5A",
      "lessonNumber": 118,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A119",
      "displayId": "5A-119",
      "level": "5A",
      "lessonNumber": 119,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A120",
      "displayId": "5A-120",
      "level": "5A",
      "lessonNumber": 120,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 2",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A121",
      "displayId": "5A-121",
      "level": "5A",
      "lessonNumber": 121,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A122",
      "displayId": "5A-122",
      "level": "5A",
      "lessonNumber": 122,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A123",
      "displayId": "5A-123",
      "level": "5A",
      "lessonNumber": 123,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A124",
      "displayId": "5A-124",
      "level": "5A",
      "lessonNumber": 124,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A125",
      "displayId": "5A-125",
      "level": "5A",
      "lessonNumber": 125,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A126",
      "displayId": "5A-126",
      "level": "5A",
      "lessonNumber": 126,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A127",
      "displayId": "5A-127",
      "level": "5A",
      "lessonNumber": 127,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A128",
      "displayId": "5A-128",
      "level": "5A",
      "lessonNumber": 128,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A129",
      "displayId": "5A-129",
      "level": "5A",
      "lessonNumber": 129,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A130",
      "displayId": "5A-130",
      "level": "5A",
      "lessonNumber": 130,
      "unit": "Sequence of Numbers up to 30 \u2014 Part 3",
      "title": "Sequence up to 30",
      "skill": "sequence_1_30",
      "mode": "sequence",
      "maxValue": 30,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A131",
      "displayId": "5A-131",
      "level": "5A",
      "lessonNumber": 131,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A132",
      "displayId": "5A-132",
      "level": "5A",
      "lessonNumber": 132,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A133",
      "displayId": "5A-133",
      "level": "5A",
      "lessonNumber": 133,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A134",
      "displayId": "5A-134",
      "level": "5A",
      "lessonNumber": 134,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A135",
      "displayId": "5A-135",
      "level": "5A",
      "lessonNumber": 135,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A136",
      "displayId": "5A-136",
      "level": "5A",
      "lessonNumber": 136,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A137",
      "displayId": "5A-137",
      "level": "5A",
      "lessonNumber": 137,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A138",
      "displayId": "5A-138",
      "level": "5A",
      "lessonNumber": 138,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A139",
      "displayId": "5A-139",
      "level": "5A",
      "lessonNumber": 139,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A140",
      "displayId": "5A-140",
      "level": "5A",
      "lessonNumber": 140,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 1",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A141",
      "displayId": "5A-141",
      "level": "5A",
      "lessonNumber": 141,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A142",
      "displayId": "5A-142",
      "level": "5A",
      "lessonNumber": 142,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A143",
      "displayId": "5A-143",
      "level": "5A",
      "lessonNumber": 143,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A144",
      "displayId": "5A-144",
      "level": "5A",
      "lessonNumber": 144,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A145",
      "displayId": "5A-145",
      "level": "5A",
      "lessonNumber": 145,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A146",
      "displayId": "5A-146",
      "level": "5A",
      "lessonNumber": 146,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A147",
      "displayId": "5A-147",
      "level": "5A",
      "lessonNumber": 147,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A148",
      "displayId": "5A-148",
      "level": "5A",
      "lessonNumber": 148,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A149",
      "displayId": "5A-149",
      "level": "5A",
      "lessonNumber": 149,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A150",
      "displayId": "5A-150",
      "level": "5A",
      "lessonNumber": 150,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 2",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A151",
      "displayId": "5A-151",
      "level": "5A",
      "lessonNumber": 151,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A152",
      "displayId": "5A-152",
      "level": "5A",
      "lessonNumber": 152,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A153",
      "displayId": "5A-153",
      "level": "5A",
      "lessonNumber": 153,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A154",
      "displayId": "5A-154",
      "level": "5A",
      "lessonNumber": 154,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A155",
      "displayId": "5A-155",
      "level": "5A",
      "lessonNumber": 155,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A156",
      "displayId": "5A-156",
      "level": "5A",
      "lessonNumber": 156,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A157",
      "displayId": "5A-157",
      "level": "5A",
      "lessonNumber": 157,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A158",
      "displayId": "5A-158",
      "level": "5A",
      "lessonNumber": 158,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A159",
      "displayId": "5A-159",
      "level": "5A",
      "lessonNumber": 159,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A160",
      "displayId": "5A-160",
      "level": "5A",
      "lessonNumber": 160,
      "unit": "Sequence of Numbers up to 40 \u2014 Part 3",
      "title": "Sequence up to 40",
      "skill": "sequence_1_40",
      "mode": "sequence",
      "maxValue": 40,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A161",
      "displayId": "5A-161",
      "level": "5A",
      "lessonNumber": 161,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A162",
      "displayId": "5A-162",
      "level": "5A",
      "lessonNumber": 162,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A163",
      "displayId": "5A-163",
      "level": "5A",
      "lessonNumber": 163,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A164",
      "displayId": "5A-164",
      "level": "5A",
      "lessonNumber": 164,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A165",
      "displayId": "5A-165",
      "level": "5A",
      "lessonNumber": 165,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A166",
      "displayId": "5A-166",
      "level": "5A",
      "lessonNumber": 166,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A167",
      "displayId": "5A-167",
      "level": "5A",
      "lessonNumber": 167,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A168",
      "displayId": "5A-168",
      "level": "5A",
      "lessonNumber": 168,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A169",
      "displayId": "5A-169",
      "level": "5A",
      "lessonNumber": 169,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A170",
      "displayId": "5A-170",
      "level": "5A",
      "lessonNumber": 170,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 1",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A171",
      "displayId": "5A-171",
      "level": "5A",
      "lessonNumber": 171,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A172",
      "displayId": "5A-172",
      "level": "5A",
      "lessonNumber": 172,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A173",
      "displayId": "5A-173",
      "level": "5A",
      "lessonNumber": 173,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A174",
      "displayId": "5A-174",
      "level": "5A",
      "lessonNumber": 174,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A175",
      "displayId": "5A-175",
      "level": "5A",
      "lessonNumber": 175,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A176",
      "displayId": "5A-176",
      "level": "5A",
      "lessonNumber": 176,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A177",
      "displayId": "5A-177",
      "level": "5A",
      "lessonNumber": 177,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A178",
      "displayId": "5A-178",
      "level": "5A",
      "lessonNumber": 178,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A179",
      "displayId": "5A-179",
      "level": "5A",
      "lessonNumber": 179,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A180",
      "displayId": "5A-180",
      "level": "5A",
      "lessonNumber": 180,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 2",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A181",
      "displayId": "5A-181",
      "level": "5A",
      "lessonNumber": 181,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A182",
      "displayId": "5A-182",
      "level": "5A",
      "lessonNumber": 182,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A183",
      "displayId": "5A-183",
      "level": "5A",
      "lessonNumber": 183,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A184",
      "displayId": "5A-184",
      "level": "5A",
      "lessonNumber": 184,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A185",
      "displayId": "5A-185",
      "level": "5A",
      "lessonNumber": 185,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A186",
      "displayId": "5A-186",
      "level": "5A",
      "lessonNumber": 186,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A187",
      "displayId": "5A-187",
      "level": "5A",
      "lessonNumber": 187,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A188",
      "displayId": "5A-188",
      "level": "5A",
      "lessonNumber": 188,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A189",
      "displayId": "5A-189",
      "level": "5A",
      "lessonNumber": 189,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A190",
      "displayId": "5A-190",
      "level": "5A",
      "lessonNumber": 190,
      "unit": "Sequence of Numbers up to 50 \u2014 Part 3",
      "title": "Sequence up to 50",
      "skill": "sequence_1_50",
      "mode": "sequence",
      "maxValue": 50,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "5A191",
      "displayId": "5A-191",
      "level": "5A",
      "lessonNumber": 191,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A192",
      "displayId": "5A-192",
      "level": "5A",
      "lessonNumber": 192,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A193",
      "displayId": "5A-193",
      "level": "5A",
      "lessonNumber": 193,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A194",
      "displayId": "5A-194",
      "level": "5A",
      "lessonNumber": 194,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A195",
      "displayId": "5A-195",
      "level": "5A",
      "lessonNumber": 195,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A196",
      "displayId": "5A-196",
      "level": "5A",
      "lessonNumber": 196,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A197",
      "displayId": "5A-197",
      "level": "5A",
      "lessonNumber": 197,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A198",
      "displayId": "5A-198",
      "level": "5A",
      "lessonNumber": 198,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A199",
      "displayId": "5A-199",
      "level": "5A",
      "lessonNumber": 199,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "5A200",
      "displayId": "5A-200",
      "level": "5A",
      "lessonNumber": 200,
      "unit": "Large Numbers",
      "title": "Large Numbers",
      "skill": "number_reading_large",
      "mode": "number_reading",
      "maxValue": 100,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    }
  ]
};
