// Auto-generated curriculum metadata. 200 entries are worksheet-equivalent pages; question counts vary by topic phase.
export const curriculum6A = {
  "id": "6A",
  "title": "Counting & Number Recognition",
  "lessonCount": 200,
  "lessons": [
    {
      "id": "6A001",
      "displayId": "6A-1",
      "level": "6A",
      "lessonNumber": 1,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A002",
      "displayId": "6A-2",
      "level": "6A",
      "lessonNumber": 2,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A003",
      "displayId": "6A-3",
      "level": "6A",
      "lessonNumber": 3,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A004",
      "displayId": "6A-4",
      "level": "6A",
      "lessonNumber": 4,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A005",
      "displayId": "6A-5",
      "level": "6A",
      "lessonNumber": 5,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A006",
      "displayId": "6A-6",
      "level": "6A",
      "lessonNumber": 6,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A007",
      "displayId": "6A-7",
      "level": "6A",
      "lessonNumber": 7,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A008",
      "displayId": "6A-8",
      "level": "6A",
      "lessonNumber": 8,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A009",
      "displayId": "6A-9",
      "level": "6A",
      "lessonNumber": 9,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A010",
      "displayId": "6A-10",
      "level": "6A",
      "lessonNumber": 10,
      "unit": "Counting up to 5 \u2014 Part 1",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A011",
      "displayId": "6A-11",
      "level": "6A",
      "lessonNumber": 11,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A012",
      "displayId": "6A-12",
      "level": "6A",
      "lessonNumber": 12,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A013",
      "displayId": "6A-13",
      "level": "6A",
      "lessonNumber": 13,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A014",
      "displayId": "6A-14",
      "level": "6A",
      "lessonNumber": 14,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A015",
      "displayId": "6A-15",
      "level": "6A",
      "lessonNumber": 15,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A016",
      "displayId": "6A-16",
      "level": "6A",
      "lessonNumber": 16,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A017",
      "displayId": "6A-17",
      "level": "6A",
      "lessonNumber": 17,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A018",
      "displayId": "6A-18",
      "level": "6A",
      "lessonNumber": 18,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A019",
      "displayId": "6A-19",
      "level": "6A",
      "lessonNumber": 19,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A020",
      "displayId": "6A-20",
      "level": "6A",
      "lessonNumber": 20,
      "unit": "Counting up to 5 \u2014 Part 2",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A021",
      "displayId": "6A-21",
      "level": "6A",
      "lessonNumber": 21,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A022",
      "displayId": "6A-22",
      "level": "6A",
      "lessonNumber": 22,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A023",
      "displayId": "6A-23",
      "level": "6A",
      "lessonNumber": 23,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A024",
      "displayId": "6A-24",
      "level": "6A",
      "lessonNumber": 24,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A025",
      "displayId": "6A-25",
      "level": "6A",
      "lessonNumber": 25,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A026",
      "displayId": "6A-26",
      "level": "6A",
      "lessonNumber": 26,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A027",
      "displayId": "6A-27",
      "level": "6A",
      "lessonNumber": 27,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A028",
      "displayId": "6A-28",
      "level": "6A",
      "lessonNumber": 28,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A029",
      "displayId": "6A-29",
      "level": "6A",
      "lessonNumber": 29,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A030",
      "displayId": "6A-30",
      "level": "6A",
      "lessonNumber": 30,
      "unit": "Counting up to 5 \u2014 Part 3",
      "title": "Counting up to 5",
      "skill": "counting_1_5",
      "mode": "count_objects",
      "maxValue": 5,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A031",
      "displayId": "6A-31",
      "level": "6A",
      "lessonNumber": 31,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A032",
      "displayId": "6A-32",
      "level": "6A",
      "lessonNumber": 32,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A033",
      "displayId": "6A-33",
      "level": "6A",
      "lessonNumber": 33,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A034",
      "displayId": "6A-34",
      "level": "6A",
      "lessonNumber": 34,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A035",
      "displayId": "6A-35",
      "level": "6A",
      "lessonNumber": 35,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A036",
      "displayId": "6A-36",
      "level": "6A",
      "lessonNumber": 36,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A037",
      "displayId": "6A-37",
      "level": "6A",
      "lessonNumber": 37,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A038",
      "displayId": "6A-38",
      "level": "6A",
      "lessonNumber": 38,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A039",
      "displayId": "6A-39",
      "level": "6A",
      "lessonNumber": 39,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A040",
      "displayId": "6A-40",
      "level": "6A",
      "lessonNumber": 40,
      "unit": "Counting up to 10 \u2014 Part 1",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A041",
      "displayId": "6A-41",
      "level": "6A",
      "lessonNumber": 41,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A042",
      "displayId": "6A-42",
      "level": "6A",
      "lessonNumber": 42,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A043",
      "displayId": "6A-43",
      "level": "6A",
      "lessonNumber": 43,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A044",
      "displayId": "6A-44",
      "level": "6A",
      "lessonNumber": 44,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A045",
      "displayId": "6A-45",
      "level": "6A",
      "lessonNumber": 45,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A046",
      "displayId": "6A-46",
      "level": "6A",
      "lessonNumber": 46,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A047",
      "displayId": "6A-47",
      "level": "6A",
      "lessonNumber": 47,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A048",
      "displayId": "6A-48",
      "level": "6A",
      "lessonNumber": 48,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A049",
      "displayId": "6A-49",
      "level": "6A",
      "lessonNumber": 49,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A050",
      "displayId": "6A-50",
      "level": "6A",
      "lessonNumber": 50,
      "unit": "Counting up to 10 \u2014 Part 2",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A051",
      "displayId": "6A-51",
      "level": "6A",
      "lessonNumber": 51,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A052",
      "displayId": "6A-52",
      "level": "6A",
      "lessonNumber": 52,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A053",
      "displayId": "6A-53",
      "level": "6A",
      "lessonNumber": 53,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A054",
      "displayId": "6A-54",
      "level": "6A",
      "lessonNumber": 54,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A055",
      "displayId": "6A-55",
      "level": "6A",
      "lessonNumber": 55,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A056",
      "displayId": "6A-56",
      "level": "6A",
      "lessonNumber": 56,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A057",
      "displayId": "6A-57",
      "level": "6A",
      "lessonNumber": 57,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A058",
      "displayId": "6A-58",
      "level": "6A",
      "lessonNumber": 58,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A059",
      "displayId": "6A-59",
      "level": "6A",
      "lessonNumber": 59,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A060",
      "displayId": "6A-60",
      "level": "6A",
      "lessonNumber": 60,
      "unit": "Counting up to 10 \u2014 Part 3",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A061",
      "displayId": "6A-61",
      "level": "6A",
      "lessonNumber": 61,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A062",
      "displayId": "6A-62",
      "level": "6A",
      "lessonNumber": 62,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A063",
      "displayId": "6A-63",
      "level": "6A",
      "lessonNumber": 63,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A064",
      "displayId": "6A-64",
      "level": "6A",
      "lessonNumber": 64,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A065",
      "displayId": "6A-65",
      "level": "6A",
      "lessonNumber": 65,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A066",
      "displayId": "6A-66",
      "level": "6A",
      "lessonNumber": 66,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A067",
      "displayId": "6A-67",
      "level": "6A",
      "lessonNumber": 67,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A068",
      "displayId": "6A-68",
      "level": "6A",
      "lessonNumber": 68,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A069",
      "displayId": "6A-69",
      "level": "6A",
      "lessonNumber": 69,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A070",
      "displayId": "6A-70",
      "level": "6A",
      "lessonNumber": 70,
      "unit": "Counting up to 10 \u2014 Part 4",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A071",
      "displayId": "6A-71",
      "level": "6A",
      "lessonNumber": 71,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A072",
      "displayId": "6A-72",
      "level": "6A",
      "lessonNumber": 72,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A073",
      "displayId": "6A-73",
      "level": "6A",
      "lessonNumber": 73,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A074",
      "displayId": "6A-74",
      "level": "6A",
      "lessonNumber": 74,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A075",
      "displayId": "6A-75",
      "level": "6A",
      "lessonNumber": 75,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A076",
      "displayId": "6A-76",
      "level": "6A",
      "lessonNumber": 76,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A077",
      "displayId": "6A-77",
      "level": "6A",
      "lessonNumber": 77,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A078",
      "displayId": "6A-78",
      "level": "6A",
      "lessonNumber": 78,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A079",
      "displayId": "6A-79",
      "level": "6A",
      "lessonNumber": 79,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A080",
      "displayId": "6A-80",
      "level": "6A",
      "lessonNumber": 80,
      "unit": "Counting up to 10 \u2014 Part 5",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A081",
      "displayId": "6A-81",
      "level": "6A",
      "lessonNumber": 81,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A082",
      "displayId": "6A-82",
      "level": "6A",
      "lessonNumber": 82,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A083",
      "displayId": "6A-83",
      "level": "6A",
      "lessonNumber": 83,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A084",
      "displayId": "6A-84",
      "level": "6A",
      "lessonNumber": 84,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A085",
      "displayId": "6A-85",
      "level": "6A",
      "lessonNumber": 85,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A086",
      "displayId": "6A-86",
      "level": "6A",
      "lessonNumber": 86,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A087",
      "displayId": "6A-87",
      "level": "6A",
      "lessonNumber": 87,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A088",
      "displayId": "6A-88",
      "level": "6A",
      "lessonNumber": 88,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A089",
      "displayId": "6A-89",
      "level": "6A",
      "lessonNumber": 89,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A090",
      "displayId": "6A-90",
      "level": "6A",
      "lessonNumber": 90,
      "unit": "Counting up to 10 \u2014 Part 6",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A091",
      "displayId": "6A-91",
      "level": "6A",
      "lessonNumber": 91,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A092",
      "displayId": "6A-92",
      "level": "6A",
      "lessonNumber": 92,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A093",
      "displayId": "6A-93",
      "level": "6A",
      "lessonNumber": 93,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A094",
      "displayId": "6A-94",
      "level": "6A",
      "lessonNumber": 94,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A095",
      "displayId": "6A-95",
      "level": "6A",
      "lessonNumber": 95,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A096",
      "displayId": "6A-96",
      "level": "6A",
      "lessonNumber": 96,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A097",
      "displayId": "6A-97",
      "level": "6A",
      "lessonNumber": 97,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A098",
      "displayId": "6A-98",
      "level": "6A",
      "lessonNumber": 98,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A099",
      "displayId": "6A-99",
      "level": "6A",
      "lessonNumber": 99,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A100",
      "displayId": "6A-100",
      "level": "6A",
      "lessonNumber": 100,
      "unit": "Counting up to 10 \u2014 Part 7",
      "title": "Counting up to 10",
      "skill": "counting_1_10",
      "mode": "count_objects",
      "maxValue": 10,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": null,
      "questionCount": 10,
      "inputMode": "choice"
    },
    {
      "id": "6A101",
      "displayId": "6A-101",
      "level": "6A",
      "lessonNumber": 101,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A102",
      "displayId": "6A-102",
      "level": "6A",
      "lessonNumber": 102,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A103",
      "displayId": "6A-103",
      "level": "6A",
      "lessonNumber": 103,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A104",
      "displayId": "6A-104",
      "level": "6A",
      "lessonNumber": 104,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A105",
      "displayId": "6A-105",
      "level": "6A",
      "lessonNumber": 105,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A106",
      "displayId": "6A-106",
      "level": "6A",
      "lessonNumber": 106,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A107",
      "displayId": "6A-107",
      "level": "6A",
      "lessonNumber": 107,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A108",
      "displayId": "6A-108",
      "level": "6A",
      "lessonNumber": 108,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A109",
      "displayId": "6A-109",
      "level": "6A",
      "lessonNumber": 109,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A110",
      "displayId": "6A-110",
      "level": "6A",
      "lessonNumber": 110,
      "unit": "Number Reading up to 10 \u2014 Part 1",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A111",
      "displayId": "6A-111",
      "level": "6A",
      "lessonNumber": 111,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A112",
      "displayId": "6A-112",
      "level": "6A",
      "lessonNumber": 112,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A113",
      "displayId": "6A-113",
      "level": "6A",
      "lessonNumber": 113,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A114",
      "displayId": "6A-114",
      "level": "6A",
      "lessonNumber": 114,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A115",
      "displayId": "6A-115",
      "level": "6A",
      "lessonNumber": 115,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A116",
      "displayId": "6A-116",
      "level": "6A",
      "lessonNumber": 116,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A117",
      "displayId": "6A-117",
      "level": "6A",
      "lessonNumber": 117,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A118",
      "displayId": "6A-118",
      "level": "6A",
      "lessonNumber": 118,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A119",
      "displayId": "6A-119",
      "level": "6A",
      "lessonNumber": 119,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A120",
      "displayId": "6A-120",
      "level": "6A",
      "lessonNumber": 120,
      "unit": "Number Reading up to 10 \u2014 Part 2",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A121",
      "displayId": "6A-121",
      "level": "6A",
      "lessonNumber": 121,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A122",
      "displayId": "6A-122",
      "level": "6A",
      "lessonNumber": 122,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A123",
      "displayId": "6A-123",
      "level": "6A",
      "lessonNumber": 123,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A124",
      "displayId": "6A-124",
      "level": "6A",
      "lessonNumber": 124,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A125",
      "displayId": "6A-125",
      "level": "6A",
      "lessonNumber": 125,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A126",
      "displayId": "6A-126",
      "level": "6A",
      "lessonNumber": 126,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A127",
      "displayId": "6A-127",
      "level": "6A",
      "lessonNumber": 127,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A128",
      "displayId": "6A-128",
      "level": "6A",
      "lessonNumber": 128,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A129",
      "displayId": "6A-129",
      "level": "6A",
      "lessonNumber": 129,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A130",
      "displayId": "6A-130",
      "level": "6A",
      "lessonNumber": 130,
      "unit": "Number Reading up to 10 \u2014 Part 3",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A131",
      "displayId": "6A-131",
      "level": "6A",
      "lessonNumber": 131,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A132",
      "displayId": "6A-132",
      "level": "6A",
      "lessonNumber": 132,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A133",
      "displayId": "6A-133",
      "level": "6A",
      "lessonNumber": 133,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A134",
      "displayId": "6A-134",
      "level": "6A",
      "lessonNumber": 134,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A135",
      "displayId": "6A-135",
      "level": "6A",
      "lessonNumber": 135,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A136",
      "displayId": "6A-136",
      "level": "6A",
      "lessonNumber": 136,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A137",
      "displayId": "6A-137",
      "level": "6A",
      "lessonNumber": 137,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A138",
      "displayId": "6A-138",
      "level": "6A",
      "lessonNumber": 138,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A139",
      "displayId": "6A-139",
      "level": "6A",
      "lessonNumber": 139,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A140",
      "displayId": "6A-140",
      "level": "6A",
      "lessonNumber": 140,
      "unit": "Number Reading up to 10 \u2014 Part 4",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A141",
      "displayId": "6A-141",
      "level": "6A",
      "lessonNumber": 141,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A142",
      "displayId": "6A-142",
      "level": "6A",
      "lessonNumber": 142,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A143",
      "displayId": "6A-143",
      "level": "6A",
      "lessonNumber": 143,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A144",
      "displayId": "6A-144",
      "level": "6A",
      "lessonNumber": 144,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A145",
      "displayId": "6A-145",
      "level": "6A",
      "lessonNumber": 145,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A146",
      "displayId": "6A-146",
      "level": "6A",
      "lessonNumber": 146,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A147",
      "displayId": "6A-147",
      "level": "6A",
      "lessonNumber": 147,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A148",
      "displayId": "6A-148",
      "level": "6A",
      "lessonNumber": 148,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A149",
      "displayId": "6A-149",
      "level": "6A",
      "lessonNumber": 149,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A150",
      "displayId": "6A-150",
      "level": "6A",
      "lessonNumber": 150,
      "unit": "Number Reading up to 10 \u2014 Part 5",
      "title": "Number Reading up to 10",
      "skill": "number_reading_1_10",
      "mode": "number_reading",
      "maxValue": 10,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A151",
      "displayId": "6A-151",
      "level": "6A",
      "lessonNumber": 151,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A152",
      "displayId": "6A-152",
      "level": "6A",
      "lessonNumber": 152,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A153",
      "displayId": "6A-153",
      "level": "6A",
      "lessonNumber": 153,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A154",
      "displayId": "6A-154",
      "level": "6A",
      "lessonNumber": 154,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A155",
      "displayId": "6A-155",
      "level": "6A",
      "lessonNumber": 155,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A156",
      "displayId": "6A-156",
      "level": "6A",
      "lessonNumber": 156,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A157",
      "displayId": "6A-157",
      "level": "6A",
      "lessonNumber": 157,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A158",
      "displayId": "6A-158",
      "level": "6A",
      "lessonNumber": 158,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A159",
      "displayId": "6A-159",
      "level": "6A",
      "lessonNumber": 159,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A160",
      "displayId": "6A-160",
      "level": "6A",
      "lessonNumber": 160,
      "unit": "Number of Dots up to 10 \u2014 Part 1",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A161",
      "displayId": "6A-161",
      "level": "6A",
      "lessonNumber": 161,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A162",
      "displayId": "6A-162",
      "level": "6A",
      "lessonNumber": 162,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A163",
      "displayId": "6A-163",
      "level": "6A",
      "lessonNumber": 163,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A164",
      "displayId": "6A-164",
      "level": "6A",
      "lessonNumber": 164,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A165",
      "displayId": "6A-165",
      "level": "6A",
      "lessonNumber": 165,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A166",
      "displayId": "6A-166",
      "level": "6A",
      "lessonNumber": 166,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A167",
      "displayId": "6A-167",
      "level": "6A",
      "lessonNumber": 167,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A168",
      "displayId": "6A-168",
      "level": "6A",
      "lessonNumber": 168,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A169",
      "displayId": "6A-169",
      "level": "6A",
      "lessonNumber": 169,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A170",
      "displayId": "6A-170",
      "level": "6A",
      "lessonNumber": 170,
      "unit": "Number of Dots up to 10 \u2014 Part 2",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A171",
      "displayId": "6A-171",
      "level": "6A",
      "lessonNumber": 171,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A172",
      "displayId": "6A-172",
      "level": "6A",
      "lessonNumber": 172,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A173",
      "displayId": "6A-173",
      "level": "6A",
      "lessonNumber": 173,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A174",
      "displayId": "6A-174",
      "level": "6A",
      "lessonNumber": 174,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A175",
      "displayId": "6A-175",
      "level": "6A",
      "lessonNumber": 175,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A176",
      "displayId": "6A-176",
      "level": "6A",
      "lessonNumber": 176,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A177",
      "displayId": "6A-177",
      "level": "6A",
      "lessonNumber": 177,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A178",
      "displayId": "6A-178",
      "level": "6A",
      "lessonNumber": 178,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A179",
      "displayId": "6A-179",
      "level": "6A",
      "lessonNumber": 179,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A180",
      "displayId": "6A-180",
      "level": "6A",
      "lessonNumber": 180,
      "unit": "Number of Dots up to 10 \u2014 Part 3",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A181",
      "displayId": "6A-181",
      "level": "6A",
      "lessonNumber": 181,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A182",
      "displayId": "6A-182",
      "level": "6A",
      "lessonNumber": 182,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A183",
      "displayId": "6A-183",
      "level": "6A",
      "lessonNumber": 183,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A184",
      "displayId": "6A-184",
      "level": "6A",
      "lessonNumber": 184,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A185",
      "displayId": "6A-185",
      "level": "6A",
      "lessonNumber": 185,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A186",
      "displayId": "6A-186",
      "level": "6A",
      "lessonNumber": 186,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A187",
      "displayId": "6A-187",
      "level": "6A",
      "lessonNumber": 187,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A188",
      "displayId": "6A-188",
      "level": "6A",
      "lessonNumber": 188,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A189",
      "displayId": "6A-189",
      "level": "6A",
      "lessonNumber": 189,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A190",
      "displayId": "6A-190",
      "level": "6A",
      "lessonNumber": 190,
      "unit": "Number of Dots up to 10 \u2014 Part 4",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A191",
      "displayId": "6A-191",
      "level": "6A",
      "lessonNumber": 191,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A192",
      "displayId": "6A-192",
      "level": "6A",
      "lessonNumber": 192,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A193",
      "displayId": "6A-193",
      "level": "6A",
      "lessonNumber": 193,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A194",
      "displayId": "6A-194",
      "level": "6A",
      "lessonNumber": 194,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A195",
      "displayId": "6A-195",
      "level": "6A",
      "lessonNumber": 195,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A196",
      "displayId": "6A-196",
      "level": "6A",
      "lessonNumber": 196,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A197",
      "displayId": "6A-197",
      "level": "6A",
      "lessonNumber": 197,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A198",
      "displayId": "6A-198",
      "level": "6A",
      "lessonNumber": 198,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A199",
      "displayId": "6A-199",
      "level": "6A",
      "lessonNumber": 199,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    },
    {
      "id": "6A200",
      "displayId": "6A-200",
      "level": "6A",
      "lessonNumber": 200,
      "unit": "Number of Dots up to 10 \u2014 Part 5",
      "title": "Number of Dots up to 10",
      "skill": "dot_recognition_1_10",
      "mode": "dot_recognition",
      "maxValue": 10,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": null,
      "questionCount": 12,
      "inputMode": "choice"
    }
  ]
};
