// Auto-generated curriculum metadata. 200 entries are worksheet-equivalent pages; question counts vary by topic phase.
export const curriculum2A = {
  "id": "2A",
  "title": "Adding up to 10",
  "lessonCount": 200,
  "lessons": [
    {
      "id": "2A001",
      "displayId": "2A-1",
      "level": "2A",
      "lessonNumber": 1,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A002",
      "displayId": "2A-2",
      "level": "2A",
      "lessonNumber": 2,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 3,
        "max": 4,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A003",
      "displayId": "2A-3",
      "level": "2A",
      "lessonNumber": 3,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A004",
      "displayId": "2A-4",
      "level": "2A",
      "lessonNumber": 4,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A005",
      "displayId": "2A-5",
      "level": "2A",
      "lessonNumber": 5,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 9,
        "max": 10,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A006",
      "displayId": "2A-6",
      "level": "2A",
      "lessonNumber": 6,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 11,
        "max": 12,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A007",
      "displayId": "2A-7",
      "level": "2A",
      "lessonNumber": 7,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 13,
        "max": 14,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A008",
      "displayId": "2A-8",
      "level": "2A",
      "lessonNumber": 8,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 15,
        "max": 16,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A009",
      "displayId": "2A-9",
      "level": "2A",
      "lessonNumber": 9,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 17,
        "max": 18,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A010",
      "displayId": "2A-10",
      "level": "2A",
      "lessonNumber": 10,
      "unit": "Review up to 3A",
      "title": "Review up to 3A",
      "skill": "review_3a",
      "mode": "addition",
      "maxValue": 20,
      "blockFrom": 1,
      "blockTo": 10,
      "numberBand": {
        "min": 19,
        "max": 20,
        "blockMin": 1,
        "blockMax": 20
      },
      "questionCount": 15,
      "inputMode": "typed"
    },
    {
      "id": "2A011",
      "displayId": "2A-11",
      "level": "2A",
      "lessonNumber": 11,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A012",
      "displayId": "2A-12",
      "level": "2A",
      "lessonNumber": 12,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A013",
      "displayId": "2A-13",
      "level": "2A",
      "lessonNumber": 13,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 3,
        "max": 4,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A014",
      "displayId": "2A-14",
      "level": "2A",
      "lessonNumber": 14,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 4,
        "max": 5,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A015",
      "displayId": "2A-15",
      "level": "2A",
      "lessonNumber": 15,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A016",
      "displayId": "2A-16",
      "level": "2A",
      "lessonNumber": 16,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A017",
      "displayId": "2A-17",
      "level": "2A",
      "lessonNumber": 17,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 8,
        "max": 9,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A018",
      "displayId": "2A-18",
      "level": "2A",
      "lessonNumber": 18,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 9,
        "max": 10,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A019",
      "displayId": "2A-19",
      "level": "2A",
      "lessonNumber": 19,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A020",
      "displayId": "2A-20",
      "level": "2A",
      "lessonNumber": 20,
      "unit": "Adding 4 \u2014 Part 1",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 11,
      "blockTo": 20,
      "numberBand": {
        "min": 11,
        "max": 12,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A021",
      "displayId": "2A-21",
      "level": "2A",
      "lessonNumber": 21,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A022",
      "displayId": "2A-22",
      "level": "2A",
      "lessonNumber": 22,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A023",
      "displayId": "2A-23",
      "level": "2A",
      "lessonNumber": 23,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 13,
        "max": 14,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A024",
      "displayId": "2A-24",
      "level": "2A",
      "lessonNumber": 24,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 14,
        "max": 14,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A025",
      "displayId": "2A-25",
      "level": "2A",
      "lessonNumber": 25,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 14,
        "max": 14,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A026",
      "displayId": "2A-26",
      "level": "2A",
      "lessonNumber": 26,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A027",
      "displayId": "2A-27",
      "level": "2A",
      "lessonNumber": 27,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A028",
      "displayId": "2A-28",
      "level": "2A",
      "lessonNumber": 28,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 15,
        "max": 16,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A029",
      "displayId": "2A-29",
      "level": "2A",
      "lessonNumber": 29,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 16,
        "max": 16,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A030",
      "displayId": "2A-30",
      "level": "2A",
      "lessonNumber": 30,
      "unit": "Adding 4 \u2014 Part 2",
      "title": "Adding 4",
      "skill": "adding_4",
      "mode": "addition",
      "maxValue": 16,
      "blockFrom": 21,
      "blockTo": 30,
      "numberBand": {
        "min": 16,
        "max": 16,
        "blockMin": 13,
        "blockMax": 16
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A031",
      "displayId": "2A-31",
      "level": "2A",
      "lessonNumber": 31,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A032",
      "displayId": "2A-32",
      "level": "2A",
      "lessonNumber": 32,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A033",
      "displayId": "2A-33",
      "level": "2A",
      "lessonNumber": 33,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 3,
        "max": 4,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A034",
      "displayId": "2A-34",
      "level": "2A",
      "lessonNumber": 34,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 4,
        "max": 5,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A035",
      "displayId": "2A-35",
      "level": "2A",
      "lessonNumber": 35,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A036",
      "displayId": "2A-36",
      "level": "2A",
      "lessonNumber": 36,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A037",
      "displayId": "2A-37",
      "level": "2A",
      "lessonNumber": 37,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 8,
        "max": 9,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A038",
      "displayId": "2A-38",
      "level": "2A",
      "lessonNumber": 38,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 9,
        "max": 10,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A039",
      "displayId": "2A-39",
      "level": "2A",
      "lessonNumber": 39,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A040",
      "displayId": "2A-40",
      "level": "2A",
      "lessonNumber": 40,
      "unit": "Adding 5 \u2014 Part 1",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 31,
      "blockTo": 40,
      "numberBand": {
        "min": 11,
        "max": 12,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A041",
      "displayId": "2A-41",
      "level": "2A",
      "lessonNumber": 41,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A042",
      "displayId": "2A-42",
      "level": "2A",
      "lessonNumber": 42,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A043",
      "displayId": "2A-43",
      "level": "2A",
      "lessonNumber": 43,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A044",
      "displayId": "2A-44",
      "level": "2A",
      "lessonNumber": 44,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 13,
        "max": 14,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A045",
      "displayId": "2A-45",
      "level": "2A",
      "lessonNumber": 45,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 14,
        "max": 14,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A046",
      "displayId": "2A-46",
      "level": "2A",
      "lessonNumber": 46,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 14,
        "max": 14,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A047",
      "displayId": "2A-47",
      "level": "2A",
      "lessonNumber": 47,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 14,
        "max": 15,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A048",
      "displayId": "2A-48",
      "level": "2A",
      "lessonNumber": 48,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A049",
      "displayId": "2A-49",
      "level": "2A",
      "lessonNumber": 49,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A050",
      "displayId": "2A-50",
      "level": "2A",
      "lessonNumber": 50,
      "unit": "Adding 5 \u2014 Part 2",
      "title": "Adding 5",
      "skill": "adding_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 41,
      "blockTo": 50,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 13,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A051",
      "displayId": "2A-51",
      "level": "2A",
      "lessonNumber": 51,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A052",
      "displayId": "2A-52",
      "level": "2A",
      "lessonNumber": 52,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A053",
      "displayId": "2A-53",
      "level": "2A",
      "lessonNumber": 53,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 4,
        "max": 5,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A054",
      "displayId": "2A-54",
      "level": "2A",
      "lessonNumber": 54,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A055",
      "displayId": "2A-55",
      "level": "2A",
      "lessonNumber": 55,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A056",
      "displayId": "2A-56",
      "level": "2A",
      "lessonNumber": 56,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 8,
        "max": 9,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A057",
      "displayId": "2A-57",
      "level": "2A",
      "lessonNumber": 57,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A058",
      "displayId": "2A-58",
      "level": "2A",
      "lessonNumber": 58,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 11,
        "max": 12,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A059",
      "displayId": "2A-59",
      "level": "2A",
      "lessonNumber": 59,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 13,
        "max": 14,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A060",
      "displayId": "2A-60",
      "level": "2A",
      "lessonNumber": 60,
      "unit": "Adding up to 5 \u2014 Part 1",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 51,
      "blockTo": 60,
      "numberBand": {
        "min": 14,
        "max": 15,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A061",
      "displayId": "2A-61",
      "level": "2A",
      "lessonNumber": 61,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A062",
      "displayId": "2A-62",
      "level": "2A",
      "lessonNumber": 62,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A063",
      "displayId": "2A-63",
      "level": "2A",
      "lessonNumber": 63,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A064",
      "displayId": "2A-64",
      "level": "2A",
      "lessonNumber": 64,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A065",
      "displayId": "2A-65",
      "level": "2A",
      "lessonNumber": 65,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A066",
      "displayId": "2A-66",
      "level": "2A",
      "lessonNumber": 66,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A067",
      "displayId": "2A-67",
      "level": "2A",
      "lessonNumber": 67,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A068",
      "displayId": "2A-68",
      "level": "2A",
      "lessonNumber": 68,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A069",
      "displayId": "2A-69",
      "level": "2A",
      "lessonNumber": 69,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A070",
      "displayId": "2A-70",
      "level": "2A",
      "lessonNumber": 70,
      "unit": "Adding up to 5 \u2014 Part 2",
      "title": "Adding up to 5",
      "skill": "adding_up_to_5",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 61,
      "blockTo": 70,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A071",
      "displayId": "2A-71",
      "level": "2A",
      "lessonNumber": 71,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A072",
      "displayId": "2A-72",
      "level": "2A",
      "lessonNumber": 72,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A073",
      "displayId": "2A-73",
      "level": "2A",
      "lessonNumber": 73,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 3,
        "max": 4,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A074",
      "displayId": "2A-74",
      "level": "2A",
      "lessonNumber": 74,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 4,
        "max": 5,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A075",
      "displayId": "2A-75",
      "level": "2A",
      "lessonNumber": 75,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A076",
      "displayId": "2A-76",
      "level": "2A",
      "lessonNumber": 76,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A077",
      "displayId": "2A-77",
      "level": "2A",
      "lessonNumber": 77,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 8,
        "max": 9,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A078",
      "displayId": "2A-78",
      "level": "2A",
      "lessonNumber": 78,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 9,
        "max": 10,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A079",
      "displayId": "2A-79",
      "level": "2A",
      "lessonNumber": 79,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A080",
      "displayId": "2A-80",
      "level": "2A",
      "lessonNumber": 80,
      "unit": "Adding 6 \u2014 Part 1",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 71,
      "blockTo": 80,
      "numberBand": {
        "min": 11,
        "max": 12,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A081",
      "displayId": "2A-81",
      "level": "2A",
      "lessonNumber": 81,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A082",
      "displayId": "2A-82",
      "level": "2A",
      "lessonNumber": 82,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A083",
      "displayId": "2A-83",
      "level": "2A",
      "lessonNumber": 83,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A084",
      "displayId": "2A-84",
      "level": "2A",
      "lessonNumber": 84,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A085",
      "displayId": "2A-85",
      "level": "2A",
      "lessonNumber": 85,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A086",
      "displayId": "2A-86",
      "level": "2A",
      "lessonNumber": 86,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 14,
        "max": 14,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A087",
      "displayId": "2A-87",
      "level": "2A",
      "lessonNumber": 87,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 14,
        "max": 14,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A088",
      "displayId": "2A-88",
      "level": "2A",
      "lessonNumber": 88,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 14,
        "max": 14,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A089",
      "displayId": "2A-89",
      "level": "2A",
      "lessonNumber": 89,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 14,
        "max": 14,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A090",
      "displayId": "2A-90",
      "level": "2A",
      "lessonNumber": 90,
      "unit": "Adding 6 \u2014 Part 2",
      "title": "Adding 6",
      "skill": "adding_6",
      "mode": "addition",
      "maxValue": 14,
      "blockFrom": 81,
      "blockTo": 90,
      "numberBand": {
        "min": 14,
        "max": 14,
        "blockMin": 13,
        "blockMax": 14
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A091",
      "displayId": "2A-91",
      "level": "2A",
      "lessonNumber": 91,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A092",
      "displayId": "2A-92",
      "level": "2A",
      "lessonNumber": 92,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A093",
      "displayId": "2A-93",
      "level": "2A",
      "lessonNumber": 93,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 3,
        "max": 4,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A094",
      "displayId": "2A-94",
      "level": "2A",
      "lessonNumber": 94,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 4,
        "max": 5,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A095",
      "displayId": "2A-95",
      "level": "2A",
      "lessonNumber": 95,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A096",
      "displayId": "2A-96",
      "level": "2A",
      "lessonNumber": 96,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 6,
        "max": 7,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A097",
      "displayId": "2A-97",
      "level": "2A",
      "lessonNumber": 97,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A098",
      "displayId": "2A-98",
      "level": "2A",
      "lessonNumber": 98,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 8,
        "max": 9,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A099",
      "displayId": "2A-99",
      "level": "2A",
      "lessonNumber": 99,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 9,
        "max": 10,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A100",
      "displayId": "2A-100",
      "level": "2A",
      "lessonNumber": 100,
      "unit": "Adding 7 \u2014 Part 1",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 91,
      "blockTo": 100,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A101",
      "displayId": "2A-101",
      "level": "2A",
      "lessonNumber": 101,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A102",
      "displayId": "2A-102",
      "level": "2A",
      "lessonNumber": 102,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A103",
      "displayId": "2A-103",
      "level": "2A",
      "lessonNumber": 103,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A104",
      "displayId": "2A-104",
      "level": "2A",
      "lessonNumber": 104,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A105",
      "displayId": "2A-105",
      "level": "2A",
      "lessonNumber": 105,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A106",
      "displayId": "2A-106",
      "level": "2A",
      "lessonNumber": 106,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A107",
      "displayId": "2A-107",
      "level": "2A",
      "lessonNumber": 107,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A108",
      "displayId": "2A-108",
      "level": "2A",
      "lessonNumber": 108,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A109",
      "displayId": "2A-109",
      "level": "2A",
      "lessonNumber": 109,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A110",
      "displayId": "2A-110",
      "level": "2A",
      "lessonNumber": 110,
      "unit": "Adding 7 \u2014 Part 2",
      "title": "Adding 7",
      "skill": "adding_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 101,
      "blockTo": 110,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 12,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A111",
      "displayId": "2A-111",
      "level": "2A",
      "lessonNumber": 111,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A112",
      "displayId": "2A-112",
      "level": "2A",
      "lessonNumber": 112,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A113",
      "displayId": "2A-113",
      "level": "2A",
      "lessonNumber": 113,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 3,
        "max": 4,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A114",
      "displayId": "2A-114",
      "level": "2A",
      "lessonNumber": 114,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 4,
        "max": 6,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A115",
      "displayId": "2A-115",
      "level": "2A",
      "lessonNumber": 115,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 6,
        "max": 7,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A116",
      "displayId": "2A-116",
      "level": "2A",
      "lessonNumber": 116,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A117",
      "displayId": "2A-117",
      "level": "2A",
      "lessonNumber": 117,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 8,
        "max": 10,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A118",
      "displayId": "2A-118",
      "level": "2A",
      "lessonNumber": 118,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A119",
      "displayId": "2A-119",
      "level": "2A",
      "lessonNumber": 119,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 11,
        "max": 12,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A120",
      "displayId": "2A-120",
      "level": "2A",
      "lessonNumber": 120,
      "unit": "Adding up to 7 \u2014 Part 1",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 111,
      "blockTo": 120,
      "numberBand": {
        "min": 12,
        "max": 13,
        "blockMin": 1,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A121",
      "displayId": "2A-121",
      "level": "2A",
      "lessonNumber": 121,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A122",
      "displayId": "2A-122",
      "level": "2A",
      "lessonNumber": 122,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A123",
      "displayId": "2A-123",
      "level": "2A",
      "lessonNumber": 123,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A124",
      "displayId": "2A-124",
      "level": "2A",
      "lessonNumber": 124,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A125",
      "displayId": "2A-125",
      "level": "2A",
      "lessonNumber": 125,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A126",
      "displayId": "2A-126",
      "level": "2A",
      "lessonNumber": 126,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A127",
      "displayId": "2A-127",
      "level": "2A",
      "lessonNumber": 127,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A128",
      "displayId": "2A-128",
      "level": "2A",
      "lessonNumber": 128,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A129",
      "displayId": "2A-129",
      "level": "2A",
      "lessonNumber": 129,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A130",
      "displayId": "2A-130",
      "level": "2A",
      "lessonNumber": 130,
      "unit": "Adding up to 7 \u2014 Part 2",
      "title": "Adding up to 7",
      "skill": "adding_up_to_7",
      "mode": "addition",
      "maxValue": 13,
      "blockFrom": 121,
      "blockTo": 130,
      "numberBand": {
        "min": 13,
        "max": 13,
        "blockMin": 13,
        "blockMax": 13
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A131",
      "displayId": "2A-131",
      "level": "2A",
      "lessonNumber": 131,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A132",
      "displayId": "2A-132",
      "level": "2A",
      "lessonNumber": 132,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A133",
      "displayId": "2A-133",
      "level": "2A",
      "lessonNumber": 133,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 3,
        "max": 4,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A134",
      "displayId": "2A-134",
      "level": "2A",
      "lessonNumber": 134,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 4,
        "max": 5,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A135",
      "displayId": "2A-135",
      "level": "2A",
      "lessonNumber": 135,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A136",
      "displayId": "2A-136",
      "level": "2A",
      "lessonNumber": 136,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 6,
        "max": 7,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A137",
      "displayId": "2A-137",
      "level": "2A",
      "lessonNumber": 137,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A138",
      "displayId": "2A-138",
      "level": "2A",
      "lessonNumber": 138,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 8,
        "max": 9,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A139",
      "displayId": "2A-139",
      "level": "2A",
      "lessonNumber": 139,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 9,
        "max": 10,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A140",
      "displayId": "2A-140",
      "level": "2A",
      "lessonNumber": 140,
      "unit": "Adding 8 \u2014 Part 1",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 11,
      "blockFrom": 131,
      "blockTo": 140,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 11
      },
      "questionCount": 20,
      "inputMode": "typed"
    },
    {
      "id": "2A141",
      "displayId": "2A-141",
      "level": "2A",
      "lessonNumber": 141,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A142",
      "displayId": "2A-142",
      "level": "2A",
      "lessonNumber": 142,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A143",
      "displayId": "2A-143",
      "level": "2A",
      "lessonNumber": 143,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A144",
      "displayId": "2A-144",
      "level": "2A",
      "lessonNumber": 144,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A145",
      "displayId": "2A-145",
      "level": "2A",
      "lessonNumber": 145,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A146",
      "displayId": "2A-146",
      "level": "2A",
      "lessonNumber": 146,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A147",
      "displayId": "2A-147",
      "level": "2A",
      "lessonNumber": 147,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A148",
      "displayId": "2A-148",
      "level": "2A",
      "lessonNumber": 148,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A149",
      "displayId": "2A-149",
      "level": "2A",
      "lessonNumber": 149,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A150",
      "displayId": "2A-150",
      "level": "2A",
      "lessonNumber": 150,
      "unit": "Adding 8 \u2014 Part 2",
      "title": "Adding 8",
      "skill": "adding_8",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 141,
      "blockTo": 150,
      "numberBand": {
        "min": 12,
        "max": 12,
        "blockMin": 12,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A151",
      "displayId": "2A-151",
      "level": "2A",
      "lessonNumber": 151,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A152",
      "displayId": "2A-152",
      "level": "2A",
      "lessonNumber": 152,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A153",
      "displayId": "2A-153",
      "level": "2A",
      "lessonNumber": 153,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 3,
        "max": 4,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A154",
      "displayId": "2A-154",
      "level": "2A",
      "lessonNumber": 154,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 4,
        "max": 5,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A155",
      "displayId": "2A-155",
      "level": "2A",
      "lessonNumber": 155,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A156",
      "displayId": "2A-156",
      "level": "2A",
      "lessonNumber": 156,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A157",
      "displayId": "2A-157",
      "level": "2A",
      "lessonNumber": 157,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 8,
        "max": 9,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A158",
      "displayId": "2A-158",
      "level": "2A",
      "lessonNumber": 158,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 9,
        "max": 10,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A159",
      "displayId": "2A-159",
      "level": "2A",
      "lessonNumber": 159,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A160",
      "displayId": "2A-160",
      "level": "2A",
      "lessonNumber": 160,
      "unit": "Adding 9",
      "title": "Adding 9",
      "skill": "adding_9",
      "mode": "addition",
      "maxValue": 12,
      "blockFrom": 151,
      "blockTo": 160,
      "numberBand": {
        "min": 11,
        "max": 12,
        "blockMin": 1,
        "blockMax": 12
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A161",
      "displayId": "2A-161",
      "level": "2A",
      "lessonNumber": 161,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A162",
      "displayId": "2A-162",
      "level": "2A",
      "lessonNumber": 162,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A163",
      "displayId": "2A-163",
      "level": "2A",
      "lessonNumber": 163,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 4,
        "max": 5,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A164",
      "displayId": "2A-164",
      "level": "2A",
      "lessonNumber": 164,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A165",
      "displayId": "2A-165",
      "level": "2A",
      "lessonNumber": 165,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A166",
      "displayId": "2A-166",
      "level": "2A",
      "lessonNumber": 166,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 8,
        "max": 9,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A167",
      "displayId": "2A-167",
      "level": "2A",
      "lessonNumber": 167,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A168",
      "displayId": "2A-168",
      "level": "2A",
      "lessonNumber": 168,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 11,
        "max": 12,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A169",
      "displayId": "2A-169",
      "level": "2A",
      "lessonNumber": 169,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 13,
        "max": 14,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A170",
      "displayId": "2A-170",
      "level": "2A",
      "lessonNumber": 170,
      "unit": "Adding 9 and 10",
      "title": "Adding 9 and 10",
      "skill": "adding_9_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 161,
      "blockTo": 170,
      "numberBand": {
        "min": 14,
        "max": 15,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A171",
      "displayId": "2A-171",
      "level": "2A",
      "lessonNumber": 171,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 1,
        "max": 2,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A172",
      "displayId": "2A-172",
      "level": "2A",
      "lessonNumber": 172,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 2,
        "max": 3,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A173",
      "displayId": "2A-173",
      "level": "2A",
      "lessonNumber": 173,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 4,
        "max": 5,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A174",
      "displayId": "2A-174",
      "level": "2A",
      "lessonNumber": 174,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 5,
        "max": 6,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A175",
      "displayId": "2A-175",
      "level": "2A",
      "lessonNumber": 175,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 7,
        "max": 8,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A176",
      "displayId": "2A-176",
      "level": "2A",
      "lessonNumber": 176,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 8,
        "max": 9,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A177",
      "displayId": "2A-177",
      "level": "2A",
      "lessonNumber": 177,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 10,
        "max": 11,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A178",
      "displayId": "2A-178",
      "level": "2A",
      "lessonNumber": 178,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 11,
        "max": 12,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A179",
      "displayId": "2A-179",
      "level": "2A",
      "lessonNumber": 179,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 13,
        "max": 14,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A180",
      "displayId": "2A-180",
      "level": "2A",
      "lessonNumber": 180,
      "unit": "Adding up to 10 \u2014 Part 1",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 171,
      "blockTo": 180,
      "numberBand": {
        "min": 14,
        "max": 15,
        "blockMin": 1,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A181",
      "displayId": "2A-181",
      "level": "2A",
      "lessonNumber": 181,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A182",
      "displayId": "2A-182",
      "level": "2A",
      "lessonNumber": 182,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A183",
      "displayId": "2A-183",
      "level": "2A",
      "lessonNumber": 183,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A184",
      "displayId": "2A-184",
      "level": "2A",
      "lessonNumber": 184,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A185",
      "displayId": "2A-185",
      "level": "2A",
      "lessonNumber": 185,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A186",
      "displayId": "2A-186",
      "level": "2A",
      "lessonNumber": 186,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A187",
      "displayId": "2A-187",
      "level": "2A",
      "lessonNumber": 187,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A188",
      "displayId": "2A-188",
      "level": "2A",
      "lessonNumber": 188,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A189",
      "displayId": "2A-189",
      "level": "2A",
      "lessonNumber": 189,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A190",
      "displayId": "2A-190",
      "level": "2A",
      "lessonNumber": 190,
      "unit": "Adding up to 10 \u2014 Part 2",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 181,
      "blockTo": 190,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A191",
      "displayId": "2A-191",
      "level": "2A",
      "lessonNumber": 191,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A192",
      "displayId": "2A-192",
      "level": "2A",
      "lessonNumber": 192,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A193",
      "displayId": "2A-193",
      "level": "2A",
      "lessonNumber": 193,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A194",
      "displayId": "2A-194",
      "level": "2A",
      "lessonNumber": 194,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A195",
      "displayId": "2A-195",
      "level": "2A",
      "lessonNumber": 195,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A196",
      "displayId": "2A-196",
      "level": "2A",
      "lessonNumber": 196,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A197",
      "displayId": "2A-197",
      "level": "2A",
      "lessonNumber": 197,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A198",
      "displayId": "2A-198",
      "level": "2A",
      "lessonNumber": 198,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A199",
      "displayId": "2A-199",
      "level": "2A",
      "lessonNumber": 199,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    },
    {
      "id": "2A200",
      "displayId": "2A-200",
      "level": "2A",
      "lessonNumber": 200,
      "unit": "Adding up to 10 \u2014 Part 3",
      "title": "Adding up to 10",
      "skill": "adding_up_to_10",
      "mode": "addition",
      "maxValue": 15,
      "blockFrom": 191,
      "blockTo": 200,
      "numberBand": {
        "min": 15,
        "max": 15,
        "blockMin": 15,
        "blockMax": 15
      },
      "questionCount": 25,
      "inputMode": "typed"
    }
  ]
};
